# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(verbose_name='post id')),
                ('user_id', models.IntegerField(verbose_name='user id')),
                ('title', models.TextField(blank=True, null=True, verbose_name='title')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
            ],
        ),
    ]
