# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_posts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20170430_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='user_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='data_post_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='data_user_id',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
