# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170430_1731'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(through='posts.UserPost', to='posts.Post'),
        ),
    ]
